spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Se o seu código usa esses nomes específicos:
api.security.token.secret=${JWT_SECRET}
api.security.token.expiration=${JWT_EXPIRATION_MS}

# Hibernate/Flyway
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true