spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}

# Configurações de JWT (A secret deve ser uma variável de ambiente)
api.security.token.secret=${JWT_SECRET}

# Hibernate/Flyway
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true