spring.application.name=financeiro

#POSTGRES
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Configura??es do JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true

api.security.token.secret=${API_SECURITY_TOKEN_SECRET}

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.probes.enabled=true